FROM ruby:2.5.5-alpine3.9

RUN apk add --no-cache --update build-base \
  linux-headers \
  git \
  postgresql-dev \
  nodejs \
  tzdata

ARG DATABASE_URL="postgres://postgres@db"
ARG RAILS_ENV=production

WORKDIR /pursuit
COPY Gemfile /pursuit/Gemfile
COPY Gemfile.lock /pursuit/Gemfile.lock

RUN gem install bundler && bundle install && bundle exec rails assets:precompile

COPY . /pursuit

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]