FROM node:11-alpine

WORKDIR /usr/src/pursuit

ARG NODE_ENV=production

ENV PATH /usr/src/pursuit/node_modules/.bin:$PATH

COPY package.json /usr/src/pursuit/package.json

RUN npm install --silent

CMD ["npm", "run", "postinstall"]