version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: cmmeur01/pursuit-web
    volumes:
      - .:/pursuit
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: cmmeur01/pursuit-frontend
    volumes:
      - ".:/usr/src/pursuit"
      - "/usr/src/pursuit/node_modules"
    environment:
      - NODE_ENV=development